- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-01771c7148909044d
    zone_id: Z0095538Q74XD6XU6M0Z
    domain_name: "dawgs.online"
    # We can pass instance through command line using -e
    # instance: 
    # - mongodb
    # - redis
    # - mysql
    # - rabbitmq
  tasks:
  - name: create ec2 instance     # list-> Structured collection of values 
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instance }}"
    register: ec2_output

  # - name: print the ec2_output
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_output }}"       


  # - name: print public_ip
  #   ansible.builtin.debug: 
  #     msg: "{{ item.instances[0].public_ip_address }}"
  #   loop: "{{ ec2_output.results }}"    

  # - name: print public_ip
  #   ansible.builtin.debug: 
  #     msg: "{{ item.instances[0].private_ip_address }}"
  #   loop: "{{ ec2_output.results }}"

- name: create route53 records for private services (not frontend)
  amazon.aws.route53:
    state: present
    zone: "{{ domain_name }}"
    record: "{{ item.item }}.{{ domain_name }}"
    type: A
    ttl: 60
    value: "{{ item.instances[0].private_ip_address }}"
    overwrite: true
  when: item.item != "frontend"
  loop: "{{ ec2_output.results }}"

- name: create route53 record for frontend (public)
  amazon.aws.route53:
    state: present
    zone: "{{ domain_name }}"
    record: "frontend.{{ domain_name }}"
    type: A
    ttl: 60
    value: "{{ item.instances[0].public_ip_address }}"
    overwrite: true
  when: item.item == "frontend"
  loop: "{{ ec2_output.results }}"    