---
- name: configure rabbitmq
  hosts: rabbitmq
  become: yes
  tasks:
    - name: configure the repo
      ansible.builtin.copy:
        src: rabbitmq.repo
        dest: /etc/yum.repos.d/rabbitmq.repo
    - name: install rabbitmq server
      ansible.builtin.package:
        name: rabbitmq-server
        state: present
    - name: enable and start the service
      ansible.builtin.service:
        enabled: yes
        state: started
    - name: add user
      ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123
    - name: set permissions
      ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"